### ISSUE TITLE
Example on how to use for multiple parameters

### ISSUE THREAD

**Issue by pip8786** [andrew-templeton/bottie#11]
Is there a way you could use this to interpret multiple parameters out of the message sent?

For example, I'd think these two would be the same "skill":
Tell me how many ducks farmer ted owns?
How many dogs does farmer bill have on his farm?

The two parameters there would be the animal type and the farmer's name. Would it be possible to get that information out of the message or would you build separate skills for those?

**Comment by andrew-templeton** [comment]
You'd need to build a different kind of bot. I'm considering doing a v2 version of this so stay tuned...

**Comment by vveerrgg** [comment]
Let me know where you land with that update.  I'm also considering getting back into the bot and updating it for 2018.
