### ISSUE TITLE
export command not working on Windows

### ISSUE THREAD

**Issue by bishwa-poudel** [andrew-templeton/bottie#8]
On running the command 
export SLACK_TOKEN='<COPIED_TOKEN from your Slack-Bot API>'
Following error message is shown:
'export' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alecl** [comment]
Though it's another dependency I've found this handy to avoid this issue:

https://www.npmjs.com/package/cross-env

**Comment by andrew-templeton** [comment]
Please use the set command instead. The shell commands differ for every type of shell (windows is diff from common linux / mac export command)
