### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by shyam-habarakada** [andrew-templeton/bottie#9]
Hi Andrew, I found your repo through a blog post you wrote. Just noticed it has no license file? Could you please add that so I could try to use it in some experiments?

Thanks

**Comment by andrew-templeton** [comment]
Make a PR for MIT and I'll approve merge - I won't be in front of computer for a day or so but can approve from phone. 

Thanks for your interest!

~~ AT

**Comment by andrew-templeton** [comment]
#10 Resolves this

**Comment by shyam-habarakada** [comment]
Thank you!
